[[redirects]]
  from = "/tiktok/link"
  to = "/tiktok/link.html"
  status = 200
  force = true

[[redirects]]
  from = "/x/link"
  to = "/x/link.html"
  status = 200
  force = true

[[redirects]]
  from = "/snapchat/link"
  to = "/snapchat/link.html"
  status = 200
  force = true

[[redirects]]
  from = "/reddit/link"
  to = "/reddit/link.html"
  status = 200
  force = true

[[redirects]]
  from = "/ig/link"
  to = "/ig/link.html"
  status = 200
  force = true
